title: 2025 Power Grid Summer School @ ECL

logo: /Assets/logo.svg

description: 2025 Summer School on "Introduction to Power Grid Dynamics, Stability and Control"

show_download: false

theme: jekyll-theme-minimal